-- Sample recipes stored the whole line ("500 g de bœuf haché") as label;
-- labels now exclude the quantity, which is shown (and scaled) separately.
UPDATE `recipe_ingredients` SET `original_label` = CASE `original_label`
  WHEN '500 g de bœuf haché' THEN 'bœuf haché'
  WHEN '2 oignons' THEN 'oignons'
  WHEN '2 gousses d''ail' THEN 'ail'
  WHEN '1 poivron rouge' THEN 'poivron rouge'
  WHEN '1 boîte de haricots rouges' THEN 'haricots rouges'
  WHEN '400 g de tomates concassées' THEN 'tomates concassées'
  WHEN '1 c. à c. de cumin' THEN 'cumin'
  WHEN '2 c. à s. d''huile d''olive' THEN 'huile d''olive'
  WHEN '1 kg de pommes de terre' THEN 'pommes de terre'
  WHEN '40 cl de crème liquide' THEN 'crème liquide'
  WHEN '30 cl de lait' THEN 'lait'
  WHEN '1 gousse d''ail' THEN 'ail'
  WHEN '1 pincée de muscade' THEN 'muscade'
  WHEN '4 pavés de saumon' THEN 'pavés de saumon'
  WHEN '1 brocoli' THEN 'brocoli'
  WHEN '1 citron' THEN 'citron'
  WHEN '1 botte d''aneth' THEN 'aneth'
  WHEN '2 boîtes de pois chiches' THEN 'pois chiches'
  WHEN '40 cl de lait de coco' THEN 'lait de coco'
  WHEN '1 oignon' THEN 'oignon'
  WHEN '20 g de gingembre frais' THEN 'gingembre frais'
  WHEN '200 g d''épinards' THEN 'épinards'
  WHEN '2 c. à s. de curry' THEN 'curry'
  WHEN '300 g de riz basmati' THEN 'riz basmati'
  WHEN '1 poulet fermier (1,5 kg)' THEN 'poulet fermier (1,5 kg)'
  WHEN '4 carottes' THEN 'carottes'
  WHEN '600 g de pommes de terre grenaille' THEN 'pommes de terre grenaille'
  WHEN '1 botte de thym' THEN 'thym'
  WHEN '3 c. à s. d''huile d''olive' THEN 'huile d''olive'
  WHEN '250 g de lentilles corail' THEN 'lentilles corail'
  WHEN '2 carottes' THEN 'carottes'
  WHEN '20 cl de lait de coco' THEN 'lait de coco'
  WHEN '1 l de bouillon de légumes' THEN 'bouillon de légumes'
  WHEN '400 g de bœuf haché' THEN 'bœuf haché'
  WHEN '1 carotte' THEN 'carotte'
  WHEN '1 branche de céleri' THEN 'branche de céleri'
  WHEN '800 g de tomates concassées' THEN 'tomates concassées'
  WHEN '400 g de spaghetti' THEN 'spaghetti'
  WHEN '50 g de parmesan' THEN 'parmesan'
  WHEN '1 pâte brisée' THEN 'pâte brisée'
  WHEN '3 poireaux' THEN 'poireaux'
  WHEN '150 g de bûche de chèvre' THEN 'bûche de chèvre'
  WHEN '3 œufs' THEN 'œufs'
  WHEN '20 cl de crème' THEN 'crème'
  WHEN '20 g de beurre' THEN 'beurre'
  ELSE `original_label` END;
